from fastapi import APIRouter, UploadFile
from sse_starlette.sse import EventSourceResponse

from app.chat.schemas import ChatResponse, ResumeRequest
from app.chat.service import chat_llm, chat_llm_stream, resume_graph
from app.common.dependencies import (
    AudioFileDep,
    LanguageFormDep,
    MessageFormDep,
    SessionIdFormDep,
    UserIdFormDep,
    read_audio,
)


chatRouter = APIRouter(prefix="/chat", tags=["chat"])


@chatRouter.post("", response_model=ChatResponse)
async def chat(
    session_id: SessionIdFormDep,
    message: MessageFormDep = "",
    user_id: UserIdFormDep = "default",
    language: LanguageFormDep = None,
    audio: AudioFileDep = None,
):
    """Process text message or audio file (or both).

    Supports both JSON body and multipart form data.

    ``session_id`` is required and generated by the frontend. It becomes the
    LangGraph thread_id: passing a new value starts a fresh conversation with
    no prior history (keeps context window small); passing the same value
    continues the existing thread. ``user_id`` only selects the persisted
    store data (profile / tasks / instructions).

    If audio is provided, it will be transcribed first via the transcription
    subgraph, then the transcript will be processed by the main agent along
    with any text message.

    Returns an ``interrupt`` field when the graph pauses for human approval.
    """
    audio_bytes, audio_filename = await read_audio(audio)

    data = await chat_llm(
        message=message,
        user_id=user_id,
        session_id=session_id,
        audio_bytes=audio_bytes,
        audio_filename=audio_filename,
        audio_language=language,
    )
    return ChatResponse(
        answer=data["reply"],
        tasks=data["tasks"],
        interrupt=data.get("interrupt"),
    )


@chatRouter.post("/resume", response_model=ChatResponse)
async def chat_resume(request: ResumeRequest):
    """Resume a paused graph with a human decision.

    Call this after the frontend renders an interrupt approval card and the
    user approves, rejects, or edits the proposed task changes.

    The ``decision`` dict is passed directly as the ``resume`` payload to
    the graph via ``Command(resume=decision)``. The ``session_id`` must be
    the same one used to start the interrupted turn.

    Example decisions:
      - ``{"approved": true}`` — accept all proposed changes
      - ``{"approved": true, "rejected_keys": ["abc-123"]}`` — reject one task
      - ``{"approved": true, "edited_tasks": [{"key": "...", "task": {...}}]}``
      - ``{"approved": false}`` — reject everything
    """
    data = await resume_graph(
        user_id=request.user_id,
        session_id=request.session_id,
        decision=request.decision,
    )
    return ChatResponse(
        answer=data["reply"],
        tasks=data["tasks"],
        interrupt=data.get("interrupt"),
    )


@chatRouter.post("/stream")
async def chat_stream(
    session_id: SessionIdFormDep,
    message: MessageFormDep = "",
    user_id: UserIdFormDep = "default",
    language: LanguageFormDep = None,
    audio: AudioFileDep = None,
):
    """Stream processing result for text message or audio file (or both).

    Supports both JSON body and multipart form data.

    If audio is provided, it will be transcribed first via the transcription
    subgraph, then the transcript will be processed by the main agent along
    with any text message.

    When a human-in-the-loop interrupt fires, an ``interrupt`` SSE event is
    yielded so the frontend can render an approval card.  After the user
    decides, POST to ``/resume`` to continue.
    """
    audio_bytes, audio_filename = await read_audio(audio)

    return EventSourceResponse(chat_llm_stream(
        message=message,
        user_id=user_id,
        session_id=session_id,
        audio_bytes=audio_bytes,
        audio_filename=audio_filename,
        audio_language=language,
    ))
