import asyncio
import json
import logging

from langchain_core.messages import AIMessage, HumanMessage
from langgraph.types import Command

from ainote.agents.models import Configuration
from ainote.agents.graph import builder
from ainote.agents.graph.state import AgentState
from ainote.agents.memory import get_tasks
from app.chat.thread import resolve_thread_id
from app.common.content_safety import filter_risky_reply

logger = logging.getLogger(__name__)


def _last_ai_content(messages: list) -> str:
    """Extract the last AI text reply from the message list, skipping tool calls."""
    for m in reversed(messages):
        if isinstance(m, AIMessage) and m.content:
            return m.content
    return ""


def _build_chat_response(
    result_value: dict,
    user_id: str,
    interrupt_data: dict | None = None,
) -> dict:
    """Build the standard ``{reply, tasks, interrupt?}`` response dict.

    Called by both ``chat_llm`` and ``resume_graph`` to avoid repeating
    the ``_last_ai_content`` / ``get_tasks`` / dict construction pattern.
    """
    reply = _last_ai_content(result_value.get("messages", []))
    tasks = get_tasks(builder.store, user_id)
    response = {"reply": reply, "tasks": tasks}
    if interrupt_data:
        response["interrupt"] = interrupt_data
    return response


# ── Non-streaming (invoke) ────────────────────────────────────────────


async def chat_llm(
    message: str = "",
    user_id: str = "default",
    session_id: str = "",
    audio_bytes: bytes | None = None,
    audio_filename: str | None = None,
    audio_language: str | None = None,
) -> dict:
    """Invoke the LangGraph agent and return reply + tasks.

    Uses ``ainvoke(version="v2")`` which returns a ``GraphOutput`` with
    clean ``.value`` / ``.interrupts`` attributes instead of the
    deprecated ``__interrupt__`` dict key.

    ``session_id`` (generated by the frontend) is combined with ``user_id``
    into the LangGraph ``thread_id`` — so conversation history is isolated
    per account, and passing a new ``session_id`` starts a fresh thread.
    ``user_id`` also selects persisted store data.

    If the graph pauses on a human-in-the-loop interrupt (e.g.
    update_tasks wants to change tasks), the returned dict will carry an
    ``interrupt`` key with the approval payload.
    """
    logger.info("chat_llm called user=%s session=%s has_audio=%s", user_id, session_id, audio_bytes is not None)

    thread_id = resolve_thread_id(user_id, session_id)
    config = {"configurable": {"thread_id": thread_id}}

    state: AgentState = {
        "messages": [HumanMessage(content=message)] if message else [],
        "user_id": user_id,
        "audio_bytes": audio_bytes,
        "audio_filename": audio_filename,
        "audio_language": audio_language,
    }

    result = await builder.graph.ainvoke(
        state,
        config=config,
        context=Configuration(user_id=user_id),
        version="v2",
    )

    # ── v2: result is GraphOutput, not a dict ──
    interrupt_data = result.interrupts[0].value if result.interrupts else None
    if interrupt_data:
        logger.info(
            "HITL interrupt returned user=%s type=%s",
            user_id, interrupt_data.get("type"),
        )
    response = _build_chat_response(result.value, user_id, interrupt_data)
    # AI 输出内容安全:命中风险 → 替换为安全占位文案。to_thread 避免阻塞事件循环。
    response["reply"] = await asyncio.to_thread(filter_risky_reply, response["reply"])
    return response


# ── Streaming (astream_events v3) ─────────────────────────────────────


async def chat_llm_stream(
    message: str = "",
    user_id: str = "default",
    session_id: str = "",
    audio_bytes: bytes | None = None,
    audio_filename: str | None = None,
    audio_language: str | None = None,
):
    """Stream the LangGraph agent output via SSE.

    Uses ``astream_events(version="v3")`` — the recommended API for
    human-in-the-loop streaming:

    - Token-by-token LLM output from ``stream.messages``
    - Clean interrupt detection via ``stream.interrupted`` /
      ``stream.interrupts`` (no ``get_state()`` hack)
    - Resume is handled by a separate ``POST /resume`` call

    ``session_id`` (generated by the frontend) is combined with ``user_id``
    into the LangGraph ``thread_id`` — so conversation history is isolated
    per account, and passing a new ``session_id`` starts a fresh thread.
    ``user_id`` also selects persisted store data.

    When a human-in-the-loop interrupt fires inside a tool, an
    ``interrupt`` SSE event is yielded so the frontend can render an
    approval card.
    """
    thread_id = resolve_thread_id(user_id, session_id)
    config = {"configurable": {"thread_id": thread_id}}

    # 立即推送连接确认，防止前端/代理因长时间无数据而超时
    yield {"event": "connected", "data": ""}
    logger.info("chat_stream started user=%s session=%s has_audio=%s", user_id, session_id, audio_bytes is not None)

    state: AgentState = {
        "messages": [HumanMessage(content=message)] if message else [],
        "user_id": user_id,
    }

    if audio_bytes:
        state["audio_bytes"] = audio_bytes
        state["audio_filename"] = audio_filename
        state["audio_language"] = audio_language

    streamed_text = ""

    try:
        # v3: returns AsyncGraphRunStream with .messages, .interrupted, etc.
        stream = await builder.graph.astream_events(
            state,
            config=config,
            context=Configuration(user_id=user_id),
            version="v3",
        )

        # ── Stream LLM tokens from .messages ──
        async for message in stream.messages:
            async for token in message.text:
                if token:
                    streamed_text += token
                    yield {"event": "message", "data": token}

        # ── After stream finishes: check for interrupt ──
        interrupted = await stream.interrupted()
        if interrupted:
            interrupts = await stream.interrupts()
            interrupt_data = interrupts[0].value
            logger.info(
                "HITL interrupt after stream user=%s type=%s",
                user_id, interrupt_data.get("type"),
            )
            yield {
                "event": "interrupt",
                "data": json.dumps(interrupt_data, ensure_ascii=False),
            }
            yield {"event": "done", "data": ""}
            logger.info(
                "chat_stream interrupted user=%s text_len=%d",
                user_id, len(streamed_text),
            )
            return

    except Exception as exc:
        # Real exception is logged server-side; only a generic message reaches
        # the client (str(exc) could leak DB connection strings / key fragments).
        logger.exception("chat_stream graph error user=%s", user_id)
        yield {"event": "error", "data": "请求处理出错，请稍后重试"}
        return

    # 流结束后推送完整 task 列表
    try:
        tasks = get_tasks(builder.store, user_id)
        yield {"event": "tasks", "data": json.dumps(tasks, ensure_ascii=False)}
    except Exception as exc:
        logger.exception("chat_stream get_tasks error user=%s", user_id)
        yield {"event": "tasks", "data": "[]"}

    yield {"event": "done", "data": ""}
    logger.info("chat_stream finished user=%s text_len=%d", user_id, len(streamed_text))


# ── Resume (invoke v2) ────────────────────────────────────────────────


async def resume_graph(
    user_id: str = "default",
    session_id: str = "",
    decision: dict | None = None,
) -> dict:
    """Resume a paused graph with a human decision.

    Uses ``ainvoke(version="v2")`` with ``Command(resume=decision)``.
    ``session_id`` must be the same one used to start the interrupted
    turn — combined with ``user_id`` it is the LangGraph ``thread_id`` that
    holds the checkpoint. If the graph hits another interrupt after resume
    (e.g. a second round of tool calls), it will be surfaced in the returned
    dict.
    """
    thread_id = resolve_thread_id(user_id, session_id)
    config = {"configurable": {"thread_id": thread_id}}

    logger.info("resume_graph user=%s decision=%s", user_id, decision)

    result = await builder.graph.ainvoke(
        Command(resume=decision or {}),
        config=config,
        context=Configuration(user_id=user_id),
        version="v2",
    )

    # v2: GraphOutput — clean .interrupts access
    interrupt_data = result.interrupts[0].value if result.interrupts else None
    if interrupt_data:
        logger.info("HITL re-interrupt after resume user=%s", user_id)
    return _build_chat_response(result.value, user_id, interrupt_data)
